[package]
name = "raito"
version = "0.1.0"
edition = "2023_11"

[scripts]
gen_data_test= "chmod -x ./scripts/data/launch.sh && bash ./scripts/data/launch.sh"

[dependencies]

[dev-dependencies]
cairo_test = "2.7.0"